#!/bin/sh
# postinst script for APPLICATION_PACKAGE
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

add_link() {
    mkdir -p "$(dirname "$2")"
    ln -sf "$1" "$2"
}

case "$1" in
    configure)
        app_name="APPLICATION_PACKAGE"
        app_dir="/opt/${app_name}"
        add_link "${app_dir}/bin/${app_name}" "/usr/bin/${app_name}"
        add_link "${app_dir}/lib/app/${app_name}.1" "/usr/share/man/man1/${app_name}.1"
        add_link "${app_dir}/lib/app/${app_name}_completion.sh" "/usr/share/bash-completion/completions/${app_name}"
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
