#!/bin/sh
# prerm script for APPLICATION_PACKAGE
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package


UTILITY_SCRIPTS

remove_link() {
    if [ -L "$2" ] && [ "$(readlink "$2")" = "$1" ]; then
        rm -f "$2"
    fi
}

case "$1" in
    remove|upgrade|deconfigure)
        app_name="APPLICATION_PACKAGE"
        app_dir="/opt/${app_name}"
        remove_link "${app_dir}/bin/${app_name}" "/usr/bin/${app_name}"
        remove_link "${app_dir}/lib/app/${app_name}.1" "/usr/share/man/man1/${app_name}.1"
        remove_link "${app_dir}/lib/app/${app_name}_completion.sh" "/usr/share/bash-completion/completions/${app_name}"
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

