name: Build and Deploy Site
on:
  push:
    tags:
    - release/*
jobs:
  build-and-deploy-site:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
        check-latest: true

    - name: Build Site
      run: mvn -B verify site

    - name: Deploy Site
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: gh-pages
        folder: target/site
