name: native-image Build
on:
  pull_request:
    branches:
    - master
jobs:
  native-image-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up cache for ~/.m2/repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: maven-${{ matrix.os }}-java11-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          maven-${{ matrix.os }}-java11-
          maven-${{ matrix.os }}-

    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 11
        check-latest: true

    - name: Maven Build
      run: mvn -B verify

    - name: Set up GraalVM
      uses: ayltai/setup-graalvm@v1
      with:
        java-version: 11
        graalvm-version: 21.1.0
        native-image: true

    - name: Install native-image prerequisites [Linux]
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get -y install build-essential libz-dev zlib1g-dev

    - name: Install native-image prerequisites [Windows]
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    - name: native-image Build [Linux]
      if: matrix.os == 'ubuntu-latest'
      run: ./target/scripts/create-native-image.sh

    - name: native-image Build [macOS]
      if: matrix.os == 'macos-latest'
      run: ./target/scripts/create-native-image.sh

    - name: native-image Build [Windows]
      if: matrix.os == 'windows-latest'
      run: .\target\scripts\create-native-image.bat
      shell: cmd
